export default function Limitations() {
  return <article className="ws-primary"><p className="ws-kicker">Scope of this build</p><h1 className="ws-heading">Know what the record can establish.</h1><p className="ws-intro">A result is only as broad as the law and facts checked. Placedon keeps that boundary attached to the result.</p>
    <section className="ws-section"><h2>Companies Act questions</h2><p>Ask can retrieve held provisions, show prescribed figures and evaluate supported duties from supplied facts. Naming a provision keeps the check precise. A text match alone does not decide whether your company complies.</p></section>
    <section className="ws-section"><h2>Dates and sources</h2><p>Live questions use today’s date. Section text may be the current consolidation held in the record; it is not a reconstruction of historical law. Dated figures carry their own governing instrument and effective date. An earlier-date selector is unavailable until complete coverage can be established.</p></section>
    <section className="ws-section"><h2>Examples and local checks</h2><p>Recorded examples use synthetic facts and a fixed date. Editing a question requires the local engine. Live checks are available only during local development; production access and company isolation still need an authenticated gateway.</p><p>Facts stay in this page’s memory until you leave or reload. There is no saved conversation, portfolio, uploaded document store or submitted-feedback service.</p></section>
    <section className="ws-section"><h2>When a result remains unresolved</h2><p>Missing company facts may be supplied and checked again. Missing legal sources require verification by Placedon. A service error means the check did not complete; it is never a legal finding.</p></section>
    <section className="ws-section"><h2>Not available here</h2><p>Drafting, case-law research, sanctions checks, filing, alerts, billing and company-register connections are not provided. Changes in law are not company-specific monitoring. No result certifies compliance or replaces professional review.</p></section>
    <a className="ws-secondary" href="/workspace/ask">Return to Ask</a>
  </article>;
}
