export default function WorkspaceHelp() {
  return <article className="ws-primary">
    <p className="ws-kicker">Help &amp; data</p><h1 className="ws-heading">Know what happens to your work.</h1>
    <p className="ws-intro">Preparing text, sending a question and saving a conversation are different actions. Check the task’s submission notice before sharing matter information.</p>
    <section className="ws-section" aria-labelledby="help-working-copy"><h2 id="help-working-copy">Working copies</h2><p>Documents currently prepares a text file or pasted text on the page. It does not upload or review that working copy. Use <strong>Clear working copy</strong> in Documents to remove the local draft and prepared copy from that screen.</p><p className="ws-muted">Clearing a screen is not deletion of a file on your computer, a copied note, browser history or a server record. Your browser may retain or restore page content.</p><a className="ws-link" href="/workspace/documents">Return to Documents</a></section>
    <details className="ws-details"><summary>Questions and conversations</summary><h2>Independent questions</h2><p>When available, Ask sends the submitted question and included company facts for processing. Independent checks do not provide conversation memory. Preparing or clearing inputs is not the same as retracting an earlier submission.</p><h2>Conversations</h2><p>When connected, Conversations sends messages to a server-held conversation. Processing may involve a model. A failed response does not prove that your message was not stored or processed.</p><p>Closing the page, starting a new question or stopping status updates does not delete saved messages or cancel server work.</p><p className="ws-muted">Access and storage are not established by the appearance of the chat. Unavailable sending or reopening is shown in the relevant task.</p><a className="ws-link" href="/workspace/conversations">Open Conversations</a></details>
    <details className="ws-details"><summary>Processing, retention and deletion</summary><p>Product processing permissions, retention periods and a deletion-request process still need approval. No product-wide retention, training-use or data-residency promise is made here.</p><p>Do not submit confidential client material until your permitted processing and access arrangements are confirmed. A captured sample is not evidence that real documents have been approved for processing.</p><p id="help-deletion-gate">Saved-data deletion is unavailable in this workspace. Clearing local text cannot confirm removal from a server, backups or a provider.</p><button className="ws-secondary" type="button" disabled aria-describedby="help-deletion-gate">Delete saved data</button></details>
    <section className="ws-section" aria-labelledby="help-feedback"><h2 id="help-feedback">Report an issue</h2><p>Describe the screen, the action you took and what you expected. Leave out client names, company facts, document text, credentials and screenshots containing matter information.</p><details className="ws-details"><summary>Prepare a feedback note</summary><label className="ws-label" htmlFor="workspace-feedback-note">Your note — not sent</label><textarea className="ws-textarea" id="workspace-feedback-note" rows={6} maxLength={2000} spellCheck={false} autoComplete="off" aria-describedby="help-feedback-gate help-feedback-storage" placeholder="Screen or feature:&#10;What I did:&#10;What happened:&#10;What I expected:" /><p id="help-feedback-storage" className="ws-muted">This screen has no feedback submission or storage service. You may select and copy your note yourself; browser restoration or copied text is outside this screen’s controls.</p><p id="help-feedback-gate">Feedback has not been sent. Sending will be available only after a support destination, consent and retention process are approved.</p><button className="ws-secondary" type="button" disabled aria-describedby="help-feedback-gate">Send feedback</button></details></section>
    <div className="ws-actions"><a className="ws-secondary" href="/workspace/limitations">Scope &amp; limitations</a><a className="ws-secondary" href="/workspace">Return to Ask</a></div>
  </article>;
}
